### ISSUE TITLE
How following code use?

### ISSUE THREAD

**Issue by alpha-xue** [island-org/island#4]
May I know how following code use? as you never defin variable cuContext and  &cuCtxSetCurrent and so on. Can it compile through?

133     bind.context = cuContext; 
134     bind.CtxSetCurrent = &cuCtxSetCurrent; 
135     bind.CtxGetCurrent = &cuCtxGetCurrent; 
136     bind.EventCreate = &cuEventCreate; 
137     bind.EventDestroy = &cuEventDestroy; 
138     bind.EventRecord = &cuEventRecord; 
139     bind.EventQuery = &cuEventQuery; 
140     bind.EventElapsedTime = &cuEventElapsedTime; 
141     rmt_BindCUDA(&bind); 
142  
143     rmt_BindOpenGL(); 

Thanks,
Alpha

**Comment by vinjn** [comment]
https://github.com/island-org/island/blob/master/include/CudaApi.h#L104
